Use gospace style layout for riakcs_ctrl
[#86649208]

diff --git a/packages/riakcs_ctrl/packaging b/packages/riakcs_ctrl/packaging
--- a/packages/riakcs_ctrl/packaging
+++ b/packages/riakcs_ctrl/packaging
@@ -1,12 +1,13 @@
-set -e # exit immediately if a simple command exits with a non-zero status
-set -u # report the usage of uninitialized variables
+set -e
+set -u
 
-#compile
+mkdir -p ${BOSH_INSTALL_TARGET}/src
+cp -a . ${BOSH_INSTALL_TARGET}/src
+export GOPATH=$BOSH_INSTALL_TARGET
+
 export GOROOT=$(readlink -nf /var/vcap/packages/golang)
 export PATH=$GOROOT/bin:$PATH
-
-export GOPATH=$PWD/riakcs_ctrl
-
 go install github.com/cloudfoundry-incubator/riakcs_ctrl
 
-cp riakcs_ctrl/bin/riakcs_ctrl $BOSH_INSTALL_TARGET/riakcs_ctrl-executable
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
