Revert "Upgrade to riak-cs 1.5.4 and riak 1.4.12."
This reverts commit d7eb1d8cb23926145a0fe36abfa6b6712d29e3c1.

- Acceptance tests fail after upgrading from RiakCS 1.5.0 and Riak
1.4.10

[#90658106]

diff --git a/packages/riak/packaging b/packages/riak/packaging
--- a/packages/riak/packaging
+++ b/packages/riak/packaging
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
 
-set +eux
+# - /var/vcap/packages/riak/rel/bin/riak
 
-RIAK_VERSION=1.4.12
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+set +x
+
+RIAK_VERSION=1.4.10
 export HOME=/var/vcap
 export PATH=/var/vcap/packages/git/bin:/var/vcap/packages/erlang/bin:$PATH
 
